version: '3'
services:
  mongo:
    container_name: mongo
    image: "mongo"
    ports:
     - "27017:27017"
  react-frontend:
    container_name: react-frontend
    image: react-frontend
    build: ./react-frontend/
    command: serve -s build
    ports:
      - "5000:5000"
  node-backend:
    container_name: node-backend
    image: node-backend
    build: ./node-backend/
    ports:
      - "3000:3000"    
    command: node app
